version: '3'

services:
    app:
        build: .
        command: uwsgi --http 0.0.0.0:8000 --wsgi-file project/wsgi.py --static-map /static=/code/static 
        ports:
            - "8001:8000"
        depends_on:
            - db
    db:
        image: postgres
        ports:
            - "5432"
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
